[package]
name = "anpa"
version = "0.1.0"
authors = ["Andreas Hallberg <habbbe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
#debug = 1

[lib]
name = "anpa"
path = "src/lib/lib.rs"

[[bin]]
name = "anpa_test"
path = "src/bin.rs"

[dependencies]
